Script started on 2016年03月06日 (週日) 22時20分29秒
]0;F74045018@2015cpp: ~F74045018@2015cpp:~$ whoami;pwd
F74045018
/home/F74045018
]0;F74045018@2015cpp: ~F74045018@2015cpp:~$ git config -I[KL[KL[KL[Kl
]0;F74045018@2015cpp: ~F74045018@2015cpp:~$ [K]0;F74045018@2015cpp: ~F74045018@2015cpp:~$ [K]0;F74045018@2015cpp: ~F74045018@2015cpp:~$ [K]0;F74045018@2015cpp: ~F74045018@2015cpp:~$ [K]0;F74045018@2015cpp: ~F74045018@2015cpp:~$ [K]0;F74045018@2015cpp: ~F74045018@2015cpp:~$ git vlo[K[K[Kclov[Kne https[Ks//[K[K://github.com/Cayonliowgitclonehttps://github.com/<your githubaccount>/lab1.git?[K]0;F74045018@2015cpp: ~F74045018@2015cpp:~$ git clone https://github.com/Cayonliowgitclonehttps://github.com/<your giithubaccount>/lab1.git?[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K/;ab[K[K[Klab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F74045018@2015cpp: ~F74045018@2015cpp:~$ 
]0;F74045018@2015cpp: ~F74045018@2015cpp:~$ exit

Script done on 2016年03月06日 (週日) 22時23分51秒
